<?
require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/header.php");
$APPLICATION->SetTitle("Товары для охоты, рыбалки, спорта, активного отдыха - интернет-магазин в {{city|предложный}}");
?>
<? $APPLICATION->IncludeComponent(
	"bitrix:news.list",
	"main_slider",
	array(
		"ACTIVE_DATE_FORMAT" => "",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"COMPONENT_TEMPLATE" => "main_slider",
		"DETAIL_URL" => "",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"DISPLAY_DATE" => "N",
		"DISPLAY_NAME" => "N",
		"DISPLAY_PICTURE" => "N",
		"DISPLAY_PREVIEW_TEXT" => "N",
		"DISPLAY_TOP_PAGER" => "N",
		"FIELD_CODE" => array(0 => "DETAIL_PICTURE", 1 => "",),
		"FILTER_NAME" => "",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "4",
		"IBLOCK_TYPE" => "content",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"INCLUDE_SUBSECTIONS" => "Y",
		"MESSAGE_404" => "",
		"NEWS_COUNT" => "20",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Новости",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"PREVIEW_TRUNCATE_LEN" => "",
		"PROPERTY_CODE" => array(0 => "LINK", 1 => "",),
		"SET_BROWSER_TITLE" => "N",
		"SET_LAST_MODIFIED" => "N",
		"SET_META_DESCRIPTION" => "N",
		"SET_META_KEYWORDS" => "N",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "N",
		"SHOW_404" => "N",
		"SORT_BY1" => "ID",
		"SORT_BY2" => "ID",
		"SORT_ORDER1" => "ASC",
		"SORT_ORDER2" => "ASC",
		"STRICT_SECTION_CHECK" => "N"
	)
); ?>
<div class="main">
	<div class="container main-page">
		<div class="row">
			<div class="col-md-12">
				<? $APPLICATION->IncludeComponent(
					"bitrix:catalog.section.list",
					"main_catalog_section_list",
					array(
						"ADD_SECTIONS_CHAIN" => "N",
						"CACHE_FILTER" => "Y",
						"CACHE_GROUPS" => "Y",
						"CACHE_TIME" => "36000000",
						"CACHE_TYPE" => "A",
						"COMPONENT_TEMPLATE" => "main_catalog_section_list",
						"COUNT_ELEMENTS" => "N",
						"FILTER_NAME" => "arrFilterSect",
						"IBLOCK_ID" => "18",
						"IBLOCK_TYPE" => "1c_catalog",
						"SECTION_CODE" => "",
						"SECTION_FIELDS" => array(0 => "", 1 => "",),
						"SECTION_ID" => $_REQUEST["SECTION_ID"],
						"SECTION_URL" => "",
						"SECTION_USER_FIELDS" => array(0 => "UF_SHOW_ON_MAIN", 1 => "UF_SHORT_NAME", 2 => "",),
						"SHOW_PARENT_NAME" => "N",
						"TOP_DEPTH" => "2",
						"VIEW_MODE" => "LINE"
					)
				); ?>
				<? if ($GLOBALS['arrFilterSect']["!=ID"]) {
					$GLOBALS['arrFilterPopular']['!=SECTION_ID'] = $GLOBALS['arrFilterSect']["!=ID"];
				} ?>
				<div class="header-sect">
					<div class='header-sect__title'>Популярные товары</div>
					<a class="header-sect__link" href="/popular/" title="Популярные товары">Популярное</a>
				</div>
				<?
				$APPLICATION->IncludeComponent(
					"bitrix:catalog.section",
					"universal",
					array(
						"ACTION_VARIABLE" => "action",
						"ADD_PICT_PROP" => "-",
						"ADD_PROPERTIES_TO_BASKET" => "Y",
						"ADD_SECTIONS_CHAIN" => "N",
						"ADD_TO_BASKET_ACTION" => "ADD",
						"AJAX_MODE" => "N",
						"AJAX_OPTION_ADDITIONAL" => "",
						"AJAX_OPTION_HISTORY" => "N",
						"AJAX_OPTION_JUMP" => "N",
						"AJAX_OPTION_STYLE" => "Y",
						"BACKGROUND_IMAGE" => "-",
						"BASKET_URL" => "/personal/cart/",
						"BROWSER_TITLE" => "-",
						"CACHE_FILTER" => "Y",
						"CACHE_GROUPS" => "Y",
						"CACHE_TIME" => "36000000",
						"CACHE_TYPE" => "A",
						"COMPARE_NAME" => "CATALOG_COMPARE_LIST",
						"COMPARE_PATH" => "/catalog/compare.php",
						"COMPATIBLE_MODE" => "Y",
						"COMPONENT_TEMPLATE" => "universal",
						"CONVERT_CURRENCY" => "N",
						"CUSTOM_FILTER" => "{\"CLASS_ID\":\"CondGroup\",\"DATA\":{\"All\":\"AND\",\"True\":\"True\"},\"CHILDREN\":[]}",
						"DETAIL_URL" => "",
						"DISABLE_INIT_JS_IN_COMPONENT" => "N",
						"DISCOUNT_PERCENT_POSITION" => "top-right",
						"DISPLAY_BOTTOM_PAGER" => "N",
						"DISPLAY_COMPARE" => "Y",
						"DISPLAY_TOP_PAGER" => "N",
						"ELEMENT_SORT_FIELD" => "show_counter",
						"ELEMENT_SORT_FIELD2" => "show_counter",
						"ELEMENT_SORT_ORDER" => "desc",
						"ELEMENT_SORT_ORDER2" => "desc",
						"ENLARGE_PRODUCT" => "STRICT",
						"FILTER_NAME" => "arrFilterPopular",
						"HIDE_NOT_AVAILABLE" => "L",
						"HIDE_NOT_AVAILABLE_OFFERS" => "L",
						"IBLOCK_ID" => "18",
						"IBLOCK_TYPE" => "1c_catalog",
						"INCLUDE_SUBSECTIONS" => "Y",
						"LABEL_PROP" => array(),
						"LABEL_PROP_MOBILE" => "",
						"LABEL_PROP_POSITION" => "top-left",
						"LAZY_LOAD" => "N",
						"LINE_ELEMENT_COUNT" => "3",
						"LOAD_ON_SCROLL" => "N",
						"MESSAGE_404" => "",
						"MESS_BTN_ADD_TO_BASKET" => "В корзину",
						"MESS_BTN_BUY" => "Купить",
						"MESS_BTN_COMPARE" => "Сравнить",
						"MESS_BTN_DETAIL" => "Подробнее",
						"MESS_BTN_SUBSCRIBE" => "Подписаться",
						"MESS_NOT_AVAILABLE" => "Нет в наличии",
						"META_DESCRIPTION" => "-",
						"META_KEYWORDS" => "-",
						"OFFERS_CART_PROPERTIES" => "",
						"OFFERS_FIELD_CODE" => array(
							0 => "",
							1 => "",
						),
						"OFFERS_LIMIT" => "5",
						"OFFERS_PROPERTY_CODE" => array(
							0 => "RAZMER",
							1 => "VYSOTA_RAMY_DYUYMOV",
						),
						"OFFERS_SORT_FIELD" => "sort",
						"OFFERS_SORT_FIELD2" => "id",
						"OFFERS_SORT_ORDER" => "asc",
						"OFFERS_SORT_ORDER2" => "desc",
						"OFFER_ADD_PICT_PROP" => "-",
						"OFFER_TREE_PROPS" => "",
						"PAGER_BASE_LINK_ENABLE" => "N",
						"PAGER_DESC_NUMBERING" => "N",
						"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
						"PAGER_SHOW_ALL" => "N",
						"PAGER_SHOW_ALWAYS" => "N",
						"PAGER_TEMPLATE" => ".default",
						"PAGER_TITLE" => "Товары",
						"PAGE_ELEMENT_COUNT" => "15",
						"PARTIAL_PRODUCT_PROPERTIES" => "Y",
						"PRICE_CODE" => array(
							0 => "Розничная цена",
						),
						"PRICE_VAT_INCLUDE" => "Y",
						"PRODUCT_BLOCKS_ORDER" => "price,props,sku,quantityLimit,buttons,quantity",
						"PRODUCT_DISPLAY_MODE" => "Y",
						"PRODUCT_ID_VARIABLE" => "id",
						"PRODUCT_PROPERTIES" => "",
						"PRODUCT_PROPS_VARIABLE" => "prop",
						"PRODUCT_QUANTITY_VARIABLE" => "quantity",
						"PRODUCT_ROW_VARIANTS" => "[{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false},{'VARIANT':'0','BIG_DATA':false}]",
						"PRODUCT_SUBSCRIPTION" => "Y",
						"PROPERTY_CODE" => array(
							0 => "MORE_PHOTO",
							1 => "",
						),
						"PROPERTY_CODE_MOBILE" => array(),
						"RCM_PROD_ID" => $_REQUEST["PRODUCT_ID"],
						"RCM_TYPE" => "personal",
						"SECTION_CODE" => $_REQUEST["SECTION_CODE"],
						"SECTION_CODE_PATH" => "",
						"SECTION_ID" => $_REQUEST["SECTION_ID"],
						"SECTION_ID_VARIABLE" => "SECTION_ID",
						"SECTION_URL" => "",
						"SECTION_USER_FIELDS" => array(
							0 => "",
							1 => "",
						),
						"SEF_MODE" => "N",
						"SEF_RULE" => "/catalog/#SECTION_CODE#/",
						"SET_BROWSER_TITLE" => "N",
						"SET_LAST_MODIFIED" => "N",
						"SET_META_DESCRIPTION" => "N",
						"SET_META_KEYWORDS" => "N",
						"SET_STATUS_404" => "N",
						"SET_TITLE" => "N",
						"SHOW_404" => "N",
						"SHOW_ALL_WO_SECTION" => "N",
						"SHOW_CLOSE_POPUP" => "N",
						"SHOW_DISCOUNT_PERCENT" => "Y",
						"SHOW_FROM_SECTION" => "N",
						"SHOW_MAX_QUANTITY" => "N",
						"SHOW_OLD_PRICE" => "Y",
						"SHOW_PRICE_COUNT" => "1",
						"SHOW_SLIDER" => "N",
						"SLIDER_INTERVAL" => "3000",
						"SLIDER_PROGRESS" => "N",
						"TEMPLATE_THEME" => "blue",
						"USE_ENHANCED_ECOMMERCE" => "N",
						"USE_MAIN_ELEMENT_SECTION" => "N",
						"USE_PRICE_COUNT" => "N",
						"USE_PRODUCT_QUANTITY" => "N",
						"DISPLAY_PRODUCTS_IN_SLIDER" => "Y",
						"USE_COMPARE_LIST" => "N",
						'HIDE_SORTING' => 'Y'
					),
					false
				);
				?>
				<div class="header-sect">
					<div class='header-sect__title'>Лучшие предложения</div>
				</div>
				<? $APPLICATION->IncludeComponent(
					"custom:catalog.section.label",
					".default",
					array(
						"CACHE_TIME" => "3600",
						"CACHE_TYPE" => "A",
						"IBLOCK_ID" => "18",
						"IBLOCK_TYPE" => "1c_catalog",
						"WRITE_YOUR_TITLE" => "",
						"COMPONENT_TEMPLATE" => ".default"
					),
					false
				); ?>
				<div class="header-sect">
					<div class="header-sect__title">
						Акции
					</div>
				</div>
				<? $APPLICATION->IncludeComponent(
					"bitrix:news.list",
					"main_slider_small",
					array(
						"ACTIVE_DATE_FORMAT" => "",
						"ADD_SECTIONS_CHAIN" => "N",
						"AJAX_MODE" => "N",
						"AJAX_OPTION_ADDITIONAL" => "",
						"AJAX_OPTION_HISTORY" => "N",
						"AJAX_OPTION_JUMP" => "N",
						"AJAX_OPTION_STYLE" => "Y",
						"CACHE_FILTER" => "N",
						"CACHE_GROUPS" => "Y",
						"CACHE_TIME" => "36000000",
						"CACHE_TYPE" => "A",
						"CHECK_DATES" => "Y",
						"COMPONENT_TEMPLATE" => "main_slider_small",
						"DETAIL_URL" => "",
						"DISPLAY_BOTTOM_PAGER" => "N",
						"DISPLAY_DATE" => "N",
						"DISPLAY_NAME" => "N",
						"DISPLAY_PICTURE" => "N",
						"DISPLAY_PREVIEW_TEXT" => "N",
						"DISPLAY_TOP_PAGER" => "N",
						"FIELD_CODE" => array(0 => "DETAIL_PICTURE", 1 => "",),
						"FILTER_NAME" => "",
						"HIDE_LINK_WHEN_NO_DETAIL" => "N",
						"IBLOCK_ID" => "5",
						"IBLOCK_TYPE" => "content",
						"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
						"INCLUDE_SUBSECTIONS" => "Y",
						"MESSAGE_404" => "",
						"NEWS_COUNT" => "20",
						"PAGER_BASE_LINK_ENABLE" => "N",
						"PAGER_DESC_NUMBERING" => "N",
						"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
						"PAGER_SHOW_ALL" => "N",
						"PAGER_SHOW_ALWAYS" => "N",
						"PAGER_TEMPLATE" => ".default",
						"PAGER_TITLE" => "Новости",
						"PARENT_SECTION" => "",
						"PARENT_SECTION_CODE" => "",
						"PREVIEW_TRUNCATE_LEN" => "",
						"PROPERTY_CODE" => array(0 => "LINK", 1 => "",),
						"SET_BROWSER_TITLE" => "N",
						"SET_LAST_MODIFIED" => "N",
						"SET_META_DESCRIPTION" => "N",
						"SET_META_KEYWORDS" => "N",
						"SET_STATUS_404" => "N",
						"SET_TITLE" => "N",
						"SHOW_404" => "N",
						"SORT_BY1" => "SORT",
						"SORT_BY2" => "ID",
						"SORT_ORDER1" => "ASC",
						"SORT_ORDER2" => "ASC",
						"STRICT_SECTION_CHECK" => "N"
					)
				); ?>
				<div class="header-sect">
					<div class="header-sect__title">
						Персональные рекомендации
					</div>
				</div>
				<?
				$APPLICATION->IncludeComponent(
					"bitrix:catalog.section",
					"universal",
					array(
						"ACTION_VARIABLE" => "action",
						"ADD_PICT_PROP" => "-",
						"ADD_PROPERTIES_TO_BASKET" => "N",
						"ADD_SECTIONS_CHAIN" => "N",
						"ADD_TO_BASKET_ACTION" => "ADD",
						"AJAX_MODE" => "N",
						"AJAX_OPTION_ADDITIONAL" => "",
						"AJAX_OPTION_HISTORY" => "N",
						"AJAX_OPTION_JUMP" => "N",
						"AJAX_OPTION_STYLE" => "Y",
						"BACKGROUND_IMAGE" => "",
						"BASKET_URL" => "/personal/cart/",
						"BRAND_PROPERTY" => "",
						"BROWSER_TITLE" => "-",
						"CACHE_FILTER" => "N",
						"CACHE_GROUPS" => "N",
						"CACHE_TIME" => "86400",
						"CACHE_TYPE" => "A",
						"COMPARE_NAME" => "CATALOG_COMPARE_LIST",
						"COMPARE_PATH" => "",
						"COMPATIBLE_MODE" => "Y",
						"COMPONENT_TEMPLATE" => "universal",
						"CONVERT_CURRENCY" => "N",
						"CURRENCY_ID" => "RUB",
						"CUSTOM_FILTER" => "{\"CLASS_ID\":\"CondGroup\",\"DATA\":{\"All\":\"AND\",\"True\":\"True\"},\"CHILDREN\":[]}",
						"DATA_LAYER_NAME" => "",
						"DETAIL_URL" => "",
						"DISABLE_INIT_JS_IN_COMPONENT" => "N",
						"DISCOUNT_PERCENT_POSITION" => "top-right",
						"DISPLAY_BOTTOM_PAGER" => "N",
						"DISPLAY_COMPARE" => "N",
						"DISPLAY_TOP_PAGER" => "N",
						"ELEMENT_SORT_FIELD" => "sort",
						"ELEMENT_SORT_FIELD2" => "id",
						"ELEMENT_SORT_ORDER" => "asc",
						"ELEMENT_SORT_ORDER2" => "desc",
						"ENLARGE_PRODUCT" => "STRICT",
						"ENLARGE_PROP" => "",
						"FILTER_NAME" => "arrFilter123",
						"HIDE_NOT_AVAILABLE" => "Y",
						"HIDE_NOT_AVAILABLE_OFFERS" => "Y",
						"HIDE_SECTION_DESCRIPTION" => "Y",
						"IBLOCK_ID" => "18",
						"IBLOCK_TYPE" => "1c_catalog",
						"INCLUDE_SUBSECTIONS" => "Y",
						"LABEL_PROP" => array(),
						"LABEL_PROP_MOBILE" => "",
						"LABEL_PROP_POSITION" => "top-left",
						"LAZY_LOAD" => "N",
						"LINE_ELEMENT_COUNT" => "3",
						"LOAD_ON_SCROLL" => "N",
						"MESSAGE_404" => "",
						"MESS_BTN_ADD_TO_BASKET" => "В корзину",
						"MESS_BTN_BUY" => "Купить",
						"MESS_BTN_COMPARE" => "Сравнение",
						"MESS_BTN_DETAIL" => "Подробнее",
						"MESS_BTN_SUBSCRIBE" => "Подписаться",
						"MESS_NOT_AVAILABLE" => "Нет в наличии",
						"MESS_RELATIVE_QUANTITY_FEW" => "",
						"MESS_RELATIVE_QUANTITY_MANY" => "",
						"MESS_SHOW_MAX_QUANTITY" => "Наличие",
						"META_DESCRIPTION" => "-",
						"META_KEYWORDS" => "-",
						"OFFERS_CART_PROPERTIES" => "",
						"OFFERS_FIELD_CODE" => array(
							0 => "",
							1 => "PROTSENT_SKIDKI",
							2 => "",
						),
						"OFFERS_LIMIT" => "0",
						"OFFERS_PROPERTY_CODE" => "",
						"OFFERS_SORT_FIELD" => "sort",
						"OFFERS_SORT_FIELD2" => "id",
						"OFFERS_SORT_ORDER" => "asc",
						"OFFERS_SORT_ORDER2" => "desc",
						"OFFER_ADD_PICT_PROP" => "MORE_PHOTO",
						"OFFER_TREE_PROPS" => "",
						"PAGER_BASE_LINK_ENABLE" => "N",
						"PAGER_DESC_NUMBERING" => "N",
						"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
						"PAGER_SHOW_ALL" => "N",
						"PAGER_SHOW_ALWAYS" => "N",
						"PAGER_TEMPLATE" => ".default",
						"PAGER_TITLE" => "Товары",
						"PAGE_ELEMENT_COUNT" => "0",
						"PARTIAL_PRODUCT_PROPERTIES" => "N",
						"PRICE_CODE" => array(
							0 => "Розничная цена",
						),
						"PRICE_VAT_INCLUDE" => "N",
						"PRODUCT_BLOCKS_ORDER" => "price,props,quantityLimit,quantity,buttons,sku",
						"PRODUCT_DISPLAY_MODE" => "Y",
						"PRODUCT_ID_VARIABLE" => "id",
						"PRODUCT_PROPERTIES" => "",
						"PRODUCT_PROPS_VARIABLE" => "prop",
						"PRODUCT_QUANTITY_VARIABLE" => "quantity",
						"PRODUCT_ROW_VARIANTS" => "[{'VARIANT':'0','BIG_DATA':true},{'VARIANT':'0','BIG_DATA':true},{'VARIANT':'0','BIG_DATA':true},{'VARIANT':'0','BIG_DATA':true},{'VARIANT':'0','BIG_DATA':true},{'VARIANT':'0','BIG_DATA':true},{'VARIANT':'0','BIG_DATA':true},{'VARIANT':'0','BIG_DATA':true},{'VARIANT':'0','BIG_DATA':true},{'VARIANT':'0','BIG_DATA':true},{'VARIANT':'0','BIG_DATA':true},{'VARIANT':'0','BIG_DATA':true}]",
						"PRODUCT_SUBSCRIPTION" => "N",
						"PROPERTY_CODE" => array(
							0 => "RAZMER_MM",
						),
						"PROPERTY_CODE_MOBILE" => array(),
						"RCM_PROD_ID" => $_REQUEST["PRODUCT_ID"],
						"RCM_TYPE" => "personal",
						"RELATIVE_QUANTITY_FACTOR" => "",
						"SECTION_CODE" => "",
						"SECTION_ID" => "",
						"SECTION_ID_VARIABLE" => "SECTION_ID",
						"SECTION_URL" => "",
						"SECTION_USER_FIELDS" => array(
							0 => "",
							1 => "",
						),
						"SEF_MODE" => "N",
						"SET_BROWSER_TITLE" => "N",
						"SET_LAST_MODIFIED" => "N",
						"SET_META_DESCRIPTION" => "N",
						"SET_META_KEYWORDS" => "N",
						"SET_STATUS_404" => "N",
						"SET_TITLE" => "N",
						"SHOW_404" => "N",
						"SHOW_ALL_WO_SECTION" => "Y",
						"SHOW_CLOSE_POPUP" => "N",
						"SHOW_DISCOUNT_PERCENT" => "N",
						"SHOW_FROM_SECTION" => "Y",
						"SHOW_MAX_QUANTITY" => "N",
						"SHOW_OLD_PRICE" => "N",
						"SHOW_PRICE_COUNT" => "1",
						"SHOW_SLIDER" => "N",
						"SLIDER_INTERVAL" => "3000",
						"SLIDER_PROGRESS" => "N",
						"TEMPLATE_THEME" => "",
						"USE_COMPARE_LIST" => "Y",
						"USE_ENHANCED_ECOMMERCE" => "N",
						"USE_MAIN_ELEMENT_SECTION" => "N",
						"USE_PRICE_COUNT" => "N",
						"USE_PRODUCT_QUANTITY" => "N",
						"DISPLAY_PRODUCTS_IN_SLIDER" => "Y",
						'HIDE_SORTING' => 'Y'
					),
					false
				);
				?>
				<div id="content">
					<div class="content">
						<? $APPLICATION->IncludeComponent(
							"bitrix:main.include",
							"",
							array(
								"AREA_FILE_RECURSIVE" => "Y",
								"AREA_FILE_SHOW" => "file",
								"AREA_FILE_SUFFIX" => "inc",
								"EDIT_TEMPLATE" => "",
								"PATH" => SITE_DIR . "include/main_about.php"
							)
						); ?>
					</div>
				</div>
			</div>
			<!--col-->
		</div>
		<!--row-->
	</div>
	<!--container-->
</div>
<!--main--><? require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/footer.php"); ?>