<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 0.2b
 */

//
// Database `shop_ordvor`
//

// `shop_ordvor`.`city`
$city = array(
  array('id' => '3','name' => 'Альметьевск','inCity' => 'Альметьевске','underCity' => 'Альметьевску','whenceCity' => 'Альметьевска','whatCity' => 'Альметьевский','code' => 'almetievskk','db_name' => NULL,'show_city' => 'false'),
  array('id' => '4','name' => 'Ангарск','inCity' => 'Ангарске','underCity' => 'Ангарску','whenceCity' => 'Ангарска','whatCity' => 'Ангарский','code' => 'angarsk','db_name' => NULL,'show_city' => 'false'),
  array('id' => '6','name' => 'Армавир','inCity' => 'Армавире','underCity' => 'Армавиру','whenceCity' => 'Армавира','whatCity' => 'Армавирский','code' => 'armavir','db_name' => NULL,'show_city' => 'false'),
  array('id' => '7','name' => 'Артём','inCity' => 'Артёме','underCity' => 'Артёму','whenceCity' => 'Артёма','whatCity' => 'Артёмовский','code' => 'artyem','db_name' => NULL,'show_city' => 'false'),
  array('id' => '8','name' => 'Архангельск','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'arkhangelsk','db_name' => NULL,'show_city' => ''),
  array('id' => '9','name' => 'Астрахань','inCity' => 'Астрахане','underCity' => 'Астрахани','whenceCity' => 'Астрахани','whatCity' => 'Астраханский','code' => 'astrakhan','db_name' => NULL,'show_city' => 'true'),
  array('id' => '10','name' => 'Ачинск','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'achinsk','db_name' => NULL,'show_city' => ''),
  array('id' => '11','name' => 'Балаково','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'balakovo','db_name' => NULL,'show_city' => 'false'),
  array('id' => '12','name' => 'Балашиха','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'balashikha','db_name' => NULL,'show_city' => 'false'),
  array('id' => '13','name' => 'Барнаул','inCity' => 'Барнауле','underCity' => 'Барнаулу','whenceCity' => 'Барнаула','whatCity' => 'Барнаульский','code' => 'barnaul','db_name' => NULL,'show_city' => 'true'),
  array('id' => '14','name' => 'Батайск','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'bataysk','db_name' => NULL,'show_city' => ''),
  array('id' => '15','name' => 'Белгород','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'belgorod','db_name' => NULL,'show_city' => ''),
  array('id' => '16','name' => 'Бердск','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'berdsk','db_name' => NULL,'show_city' => ''),
  array('id' => '17','name' => 'Березники','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'berezniki','db_name' => NULL,'show_city' => ''),
  array('id' => '18','name' => 'Бийск','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'biysk','db_name' => NULL,'show_city' => ''),
  array('id' => '19','name' => 'Благовещенск','inCity' => 'Благовещенске','underCity' => 'Благовещенску','whenceCity' => 'Благовещенска','whatCity' => 'Благовещенск','code' => 'blagoveshensk','db_name' => NULL,'show_city' => 'true'),
  array('id' => '20','name' => 'Братск','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'bratsk','db_name' => NULL,'show_city' => 'false'),
  array('id' => '21','name' => 'Брянск','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'bryansk','db_name' => NULL,'show_city' => ''),
  array('id' => '22','name' => 'Великий Новгород','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'velikiy-novgorod','db_name' => NULL,'show_city' => ''),
  array('id' => '23','name' => 'Владивосток','inCity' => 'Владивостоке','underCity' => 'Владивостоку','whenceCity' => 'Владивостока','whatCity' => 'Владивосток','code' => 'vladivostok','db_name' => NULL,'show_city' => 'true'),
  array('id' => '24','name' => 'Владикавказ','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'vladikavkaz','db_name' => NULL,'show_city' => ''),
  array('id' => '25','name' => 'Владимир','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'vladimir','db_name' => NULL,'show_city' => ''),
  array('id' => '26','name' => 'Волгоград','inCity' => 'Волгограде','underCity' => 'Волгограду','whenceCity' => 'Волгограда','whatCity' => 'Волгоградский','code' => 'volgograd','db_name' => NULL,'show_city' => 'true'),
  array('id' => '27','name' => 'Волгодонск','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'volgodonsk','db_name' => NULL,'show_city' => ''),
  array('id' => '28','name' => 'Волжский','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'volzhskiy','db_name' => NULL,'show_city' => ''),
  array('id' => '29','name' => 'Вологда','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'vologda','db_name' => NULL,'show_city' => ''),
  array('id' => '30','name' => 'Воронеж','inCity' => 'Воронеже','underCity' => 'Воронежу','whenceCity' => 'Воронежа','whatCity' => 'Воронежский','code' => 'voronezh','db_name' => NULL,'show_city' => 'true'),
  array('id' => '31','name' => 'Грозный','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'groznyy','db_name' => NULL,'show_city' => ''),
  array('id' => '32','name' => 'Дербент','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'derbent','db_name' => NULL,'show_city' => ''),
  array('id' => '33','name' => 'Дзержинск','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'dzerzhinsk','db_name' => NULL,'show_city' => ''),
  array('id' => '34','name' => 'Димитровград','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'dimitrovgrad','db_name' => NULL,'show_city' => ''),
  array('id' => '35','name' => 'Долгопрудный','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'dolgoprudnyy','db_name' => NULL,'show_city' => ''),
  array('id' => '36','name' => 'Домодедово','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'domodedovo','db_name' => NULL,'show_city' => ''),
  array('id' => '37','name' => 'Евпатория','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'evpatoriya','db_name' => NULL,'show_city' => ''),
  array('id' => '38','name' => 'Екатеринбург','inCity' => 'Екатеринбурге','underCity' => 'Екатеринбургу','whenceCity' => 'Екатеринбурга','whatCity' => 'Екатеринбург','code' => 'ekb','db_name' => NULL,'show_city' => 'true'),
  array('id' => '39','name' => 'Елец','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'elets','db_name' => NULL,'show_city' => ''),
  array('id' => '40','name' => 'Ессентуки','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'essentuki','db_name' => NULL,'show_city' => ''),
  array('id' => '41','name' => 'Железногорск','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'zheleznogorsk','db_name' => NULL,'show_city' => ''),
  array('id' => '42','name' => 'Жуковский','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'zhukovskiy','db_name' => NULL,'show_city' => ''),
  array('id' => '43','name' => 'Златоуст','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'zlatoust','db_name' => NULL,'show_city' => ''),
  array('id' => '44','name' => 'Иваново','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'ivanovo','db_name' => NULL,'show_city' => 'false'),
  array('id' => '45','name' => 'Ижевск','inCity' => 'Ижевске','underCity' => 'Ижевску','whenceCity' => 'Ижевска','whatCity' => 'Ижевский','code' => 'izhevsk','db_name' => NULL,'show_city' => 'true'),
  array('id' => '46','name' => 'Йошкар-Ола','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'yoshkar-ola','db_name' => NULL,'show_city' => 'false'),
  array('id' => '47','name' => 'Иркутск','inCity' => 'Иркутске','underCity' => 'Иркутску','whenceCity' => 'Иркутска','whatCity' => 'Иркутский','code' => 'irkutsk','db_name' => NULL,'show_city' => 'true'),
  array('id' => '48','name' => 'Казань','inCity' => 'Казани','underCity' => 'Казани','whenceCity' => 'Казани','whatCity' => 'Казань','code' => 'kazan','db_name' => NULL,'show_city' => 'true'),
  array('id' => '49','name' => 'Калининград','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'kaliningrad','db_name' => NULL,'show_city' => 'false'),
  array('id' => '50','name' => 'Калуга','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'kaluga','db_name' => NULL,'show_city' => 'false'),
  array('id' => '51','name' => 'Каменск-Уральский','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'kamensk-uralskiy','db_name' => NULL,'show_city' => 'false'),
  array('id' => '52','name' => 'Камышин','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'kamyshin','db_name' => NULL,'show_city' => 'false'),
  array('id' => '53','name' => 'Каспийск','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'kaspiysk','db_name' => NULL,'show_city' => 'false'),
  array('id' => '54','name' => 'Кемерово','inCity' => 'Кемерове','underCity' => 'Кемерово','whenceCity' => 'Кемерово','whatCity' => 'Кемеровский','code' => 'kemerovo','db_name' => NULL,'show_city' => 'true'),
  array('id' => '55','name' => 'Керчь','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'kerch','db_name' => NULL,'show_city' => 'false'),
  array('id' => '56','name' => 'Киров','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'kirov','db_name' => NULL,'show_city' => 'false'),
  array('id' => '57','name' => 'Кисловодск','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'kislovodsk','db_name' => NULL,'show_city' => ''),
  array('id' => '58','name' => 'Ковров','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'kovrov','db_name' => NULL,'show_city' => ''),
  array('id' => '59','name' => 'Коломна','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'kolomna','db_name' => NULL,'show_city' => ''),
  array('id' => '60','name' => 'Комсомольск-на-Амуре','inCity' => 'Комсомольске-на-Амуре','underCity' => 'Комсомольску-на-Амуре','whenceCity' => 'Комсомольска-на-Амуре','whatCity' => 'Комсомольск-на-Амуре','code' => 'komsomolsknaamure','db_name' => 'komsomolsknaamure_ordvor','show_city' => 'true'),
  array('id' => '61','name' => 'Копейск','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'kopeysk','db_name' => NULL,'show_city' => ''),
  array('id' => '62','name' => 'Королёв','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'korolyev','db_name' => NULL,'show_city' => ''),
  array('id' => '63','name' => 'Кострома','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'kostroma','db_name' => NULL,'show_city' => ''),
  array('id' => '64','name' => 'Красногорск','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'krasnogorsk','db_name' => NULL,'show_city' => ''),
  array('id' => '65','name' => 'Краснодар','inCity' => 'Краснодаре','underCity' => 'Краснодару','whenceCity' => 'Краснодара','whatCity' => 'Краснодарский','code' => 'krasnodar','db_name' => NULL,'show_city' => 'true'),
  array('id' => '66','name' => 'Красноярск','inCity' => 'Красноярске','underCity' => 'Красноярску','whenceCity' => 'Красноярска','whatCity' => 'Красноярский','code' => 'krasnoyarsk','db_name' => NULL,'show_city' => 'true'),
  array('id' => '67','name' => 'Курган','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'kurgan','db_name' => NULL,'show_city' => ''),
  array('id' => '68','name' => 'Курск','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'kursk','db_name' => NULL,'show_city' => ''),
  array('id' => '69','name' => 'Кызыл','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'kyzyl','db_name' => NULL,'show_city' => ''),
  array('id' => '70','name' => 'Липецк','inCity' => 'Липецке','underCity' => 'Липецку','whenceCity' => 'Липецка','whatCity' => 'Липецкий','code' => 'lipetsk','db_name' => NULL,'show_city' => 'true'),
  array('id' => '71','name' => 'Люберцы','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'lyubertsy','db_name' => NULL,'show_city' => 'false'),
  array('id' => '72','name' => 'Майкоп','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'maykop','db_name' => NULL,'show_city' => 'false'),
  array('id' => '73','name' => 'Махачкала','inCity' => 'Махачкале','underCity' => 'Махачкале','whenceCity' => 'Махачкалы','whatCity' => 'Махачкаловский','code' => 'makhachkala','db_name' => NULL,'show_city' => 'true'),
  array('id' => '74','name' => 'Миасс','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'miass','db_name' => NULL,'show_city' => 'false'),
  array('id' => '75','name' => 'Москва','inCity' => 'Москве','underCity' => 'Москве','whenceCity' => 'Москвы','whatCity' => 'Москва','code' => 'moskva','db_name' => NULL,'show_city' => 'true'),
  array('id' => '76','name' => 'Мурманск','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'murmansk','db_name' => NULL,'show_city' => 'false'),
  array('id' => '77','name' => 'Муром','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'murom','db_name' => NULL,'show_city' => ''),
  array('id' => '78','name' => 'Мытищи','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'mytishchi','db_name' => NULL,'show_city' => ''),
  array('id' => '79','name' => 'Набережные Челны','inCity' => 'Набережных Челнах','underCity' => 'Набережным Челнам','whenceCity' => 'Набережных Челнов','whatCity' => 'Набережночелнинский','code' => 'naberezhnye-chelny','db_name' => NULL,'show_city' => 'true'),
  array('id' => '80','name' => 'Назрань','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'nazran','db_name' => NULL,'show_city' => ''),
  array('id' => '81','name' => 'Нальчик','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'nalchik','db_name' => NULL,'show_city' => 'false'),
  array('id' => '82','name' => 'Находка','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'nakhodka','db_name' => NULL,'show_city' => 'false'),
  array('id' => '83','name' => 'Невинномысск','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'nevinnomyssk','db_name' => NULL,'show_city' => 'false'),
  array('id' => '84','name' => 'Нефтекамск','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'neftekamsk','db_name' => NULL,'show_city' => 'false'),
  array('id' => '85','name' => 'Нефтеюганск','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'nefteyugansk','db_name' => NULL,'show_city' => 'false'),
  array('id' => '86','name' => 'Нижневартовск','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'nizhnevartovsk','db_name' => NULL,'show_city' => 'false'),
  array('id' => '87','name' => 'Нижнекамск','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'nizhnekamsk','db_name' => NULL,'show_city' => 'false'),
  array('id' => '88','name' => 'Нижний Новгород','inCity' => 'Нижнем Новгороде','underCity' => 'Нижниму Новгороду','whenceCity' => 'Нижнего Новгорода','whatCity' => 'Нижний Новгород','code' => 'nn','db_name' => NULL,'show_city' => 'true'),
  array('id' => '89','name' => 'Нижний Тагил','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'nizhniy-tagil','db_name' => NULL,'show_city' => 'false'),
  array('id' => '90','name' => 'Новокузнецк','inCity' => 'Новокузнецке','underCity' => 'Новокузнецку','whenceCity' => 'Новокузнецка','whatCity' => 'Новокузнецкий','code' => 'novokuznetsk','db_name' => NULL,'show_city' => 'true'),
  array('id' => '91','name' => 'Новокуйбышевск','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'novokuybyshevsk','db_name' => NULL,'show_city' => ''),
  array('id' => '92','name' => 'Новомосковск','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'novomoskovsk','db_name' => NULL,'show_city' => ''),
  array('id' => '93','name' => 'Новороссийск','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'novorossiysk','db_name' => NULL,'show_city' => ''),
  array('id' => '94','name' => 'Новосибирск','inCity' => 'Новосибирске','underCity' => 'Новосибирску','whenceCity' => 'Новосибирска','whatCity' => 'Новосибирск','code' => 'novosibirsk','db_name' => NULL,'show_city' => 'true'),
  array('id' => '95','name' => 'Новочебоксарск','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'novocheboksarsk','db_name' => NULL,'show_city' => ''),
  array('id' => '96','name' => 'Новочеркасск','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'novocherkassk','db_name' => NULL,'show_city' => ''),
  array('id' => '97','name' => 'Новошахтинск','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'novoshakhtinsk','db_name' => NULL,'show_city' => ''),
  array('id' => '98','name' => 'Новый Уренгой','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'novyy-urengoy','db_name' => NULL,'show_city' => ''),
  array('id' => '99','name' => 'Ногинск','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'noginsk','db_name' => NULL,'show_city' => ''),
  array('id' => '100','name' => 'Норильск','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'norilsk','db_name' => NULL,'show_city' => ''),
  array('id' => '101','name' => 'Ноябрьск','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'noyabrsk','db_name' => NULL,'show_city' => ''),
  array('id' => '102','name' => 'Обнинск','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'obninsk','db_name' => NULL,'show_city' => 'false'),
  array('id' => '103','name' => 'Октябрьский','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'oktyabrskiy','db_name' => NULL,'show_city' => 'false'),
  array('id' => '104','name' => 'Омск','inCity' => 'Омске','underCity' => 'Омску','whenceCity' => 'Омска','whatCity' => 'Омск','code' => 'omsk','db_name' => NULL,'show_city' => 'true'),
  array('id' => '105','name' => 'Орёл','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'oryel','db_name' => NULL,'show_city' => 'false'),
  array('id' => '106','name' => 'Оренбург','inCity' => 'Оренбурге','underCity' => 'Оренбургу','whenceCity' => 'Оренбурга','whatCity' => 'Оренбургский','code' => 'orenburg','db_name' => NULL,'show_city' => 'true'),
  array('id' => '107','name' => 'Орехово-Зуево','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'orekhovo-zuevo','db_name' => NULL,'show_city' => 'false'),
  array('id' => '108','name' => 'Орск','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'orsk','db_name' => NULL,'show_city' => 'false'),
  array('id' => '109','name' => 'Пенза','inCity' => 'Пензу','underCity' => 'Пензе','whenceCity' => 'Пензы','whatCity' => 'Пензенский','code' => 'penza','db_name' => NULL,'show_city' => 'true'),
  array('id' => '110','name' => 'Первоуральск','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'pervouralsk','db_name' => NULL,'show_city' => 'false'),
  array('id' => '111','name' => 'Пермь','inCity' => 'Перми','underCity' => 'Перми','whenceCity' => 'Перми','whatCity' => 'Пермский','code' => 'perm','db_name' => NULL,'show_city' => 'true'),
  array('id' => '112','name' => 'Петрозаводск','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'petrozavodsk','db_name' => NULL,'show_city' => 'false'),
  array('id' => '113','name' => 'Петропавловск-Камчатский','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'petropavlovsk-kamchatskiy','db_name' => NULL,'show_city' => 'false'),
  array('id' => '114','name' => 'Подольск','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'podolsk','db_name' => NULL,'show_city' => ''),
  array('id' => '115','name' => 'Прокопьевск','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'prokopevsk','db_name' => NULL,'show_city' => ''),
  array('id' => '116','name' => 'Псков','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'pskov','db_name' => NULL,'show_city' => ''),
  array('id' => '117','name' => 'Пушкино','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'pushkino','db_name' => NULL,'show_city' => ''),
  array('id' => '118','name' => 'Пятигорск','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'pyatigorsk','db_name' => NULL,'show_city' => ''),
  array('id' => '119','name' => 'Раменское','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'ramenskoe','db_name' => NULL,'show_city' => ''),
  array('id' => '120','name' => 'Реутов','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'reutov','db_name' => NULL,'show_city' => ''),
  array('id' => '121','name' => 'Ростов-на-Дону','inCity' => 'Ростов-на-Дону','underCity' => 'Ростов-на-Дону','whenceCity' => 'Ростов-на-Дону','whatCity' => 'Ростов-на-Дону','code' => 'rostov-na-donu','db_name' => NULL,'show_city' => 'true'),
  array('id' => '122','name' => 'Рубцовск','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'rubtsovsk','db_name' => NULL,'show_city' => 'false'),
  array('id' => '123','name' => 'Рыбинск','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'rybinsk','db_name' => NULL,'show_city' => ''),
  array('id' => '124','name' => 'Рязань','inCity' => 'Рязани','underCity' => 'Рязани','whenceCity' => 'Рязани','whatCity' => 'Рязанский','code' => 'ryazan','db_name' => NULL,'show_city' => 'true'),
  array('id' => '125','name' => 'Салават','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'salavat','db_name' => NULL,'show_city' => ''),
  array('id' => '126','name' => 'Самара','inCity' => 'Самаре','underCity' => 'Самаре','whenceCity' => 'Самары','whatCity' => 'Самара','code' => 'samara','db_name' => NULL,'show_city' => 'true'),
  array('id' => '127','name' => 'Санкт-Петербург','inCity' => 'Санкт-Петербурге','underCity' => 'Санкт-Петербургу','whenceCity' => 'Санкт-Петербургa','whatCity' => 'Санкт-Петербург','code' => 'spb','db_name' => NULL,'show_city' => 'true'),
  array('id' => '128','name' => 'Саранск','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'saransk','db_name' => NULL,'show_city' => 'false'),
  array('id' => '129','name' => 'Саратов','inCity' => 'Саратове','underCity' => 'Саратову','whenceCity' => 'Саратова','whatCity' => 'Саратовский','code' => 'saratov','db_name' => NULL,'show_city' => 'true'),
  array('id' => '130','name' => 'Севастополь','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'sevastopol','db_name' => NULL,'show_city' => 'false'),
  array('id' => '131','name' => 'Северодвинск','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'severodvinsk','db_name' => NULL,'show_city' => 'false'),
  array('id' => '132','name' => 'Северск','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'seversk','db_name' => NULL,'show_city' => ''),
  array('id' => '133','name' => 'Сергиев Посад','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'sergiev-posad','db_name' => NULL,'show_city' => ''),
  array('id' => '134','name' => 'Серпухов','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'serpukhov','db_name' => NULL,'show_city' => ''),
  array('id' => '135','name' => 'Симферополь','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'simferopol','db_name' => NULL,'show_city' => 'false'),
  array('id' => '136','name' => 'Смоленск','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'smolensk','db_name' => NULL,'show_city' => 'false'),
  array('id' => '137','name' => 'Сочи','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'sochi','db_name' => NULL,'show_city' => 'false'),
  array('id' => '138','name' => 'Ставрополь','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'stavropol','db_name' => NULL,'show_city' => ''),
  array('id' => '139','name' => 'Старый Оскол','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'staryy-oskol','db_name' => NULL,'show_city' => ''),
  array('id' => '140','name' => 'Стерлитамак','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'sterlitamak','db_name' => NULL,'show_city' => ''),
  array('id' => '141','name' => 'Сургут','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'surgut','db_name' => NULL,'show_city' => ''),
  array('id' => '142','name' => 'Сызрань','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'syzran','db_name' => NULL,'show_city' => ''),
  array('id' => '143','name' => 'Сыктывкар','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'syktyvkar','db_name' => NULL,'show_city' => ''),
  array('id' => '144','name' => 'Таганрог','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'taganrog','db_name' => NULL,'show_city' => 'false'),
  array('id' => '145','name' => 'Тамбов','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'tambov','db_name' => NULL,'show_city' => ''),
  array('id' => '146','name' => 'Тверь','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'tver','db_name' => NULL,'show_city' => ''),
  array('id' => '147','name' => 'Тольятти','inCity' => 'Тольятти','underCity' => 'Тольятти','whenceCity' => 'Тольятти','whatCity' => 'Тольяттинский','code' => 'tolyatti','db_name' => NULL,'show_city' => 'true'),
  array('id' => '148','name' => 'Томск','inCity' => 'Томске','underCity' => 'Томску','whenceCity' => 'Томска','whatCity' => 'Томский','code' => 'tomsk','db_name' => NULL,'show_city' => 'true'),
  array('id' => '149','name' => 'Тула','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'tula','db_name' => NULL,'show_city' => 'false'),
  array('id' => '150','name' => 'Тюмень','inCity' => 'Тюмени','underCity' => 'Тюмени','whenceCity' => 'Тюмени','whatCity' => 'Тюменский','code' => 'tyumen','db_name' => NULL,'show_city' => 'true'),
  array('id' => '151','name' => 'Улан-Удэ','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'ulan-ude','db_name' => NULL,'show_city' => 'false'),
  array('id' => '152','name' => 'Ульяновск','inCity' => 'Ульяновске','underCity' => 'Ульяновску','whenceCity' => 'Ульяновска','whatCity' => 'Ульяновский','code' => 'ulyanovsk','db_name' => NULL,'show_city' => 'true'),
  array('id' => '153','name' => 'Уссурийск','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'ussuriysk','db_name' => NULL,'show_city' => 'false'),
  array('id' => '154','name' => 'Уфа','inCity' => 'Уфе','underCity' => 'Уфе','whenceCity' => 'Уфу','whatCity' => 'Уфа','code' => 'ufa','db_name' => NULL,'show_city' => 'true'),
  array('id' => '155','name' => 'Хабаровск','inCity' => 'Хабаровске','underCity' => 'Хабаровску','whenceCity' => 'Хабаровска','whatCity' => 'Хабаровский','code' => 'shop','db_name' => 'ordvor','show_city' => 'true'),
  array('id' => '156','name' => 'Хасавюрт','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'khasavyurt','db_name' => NULL,'show_city' => ''),
  array('id' => '157','name' => 'Химки','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'khimki','db_name' => NULL,'show_city' => ''),
  array('id' => '158','name' => 'Чебоксары','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'cheboksary','db_name' => NULL,'show_city' => 'false'),
  array('id' => '159','name' => 'Челябинск','inCity' => 'Челябинске','underCity' => 'Челябинску','whenceCity' => 'Челябинска','whatCity' => 'Челябинск','code' => 'chelyabinsk','db_name' => NULL,'show_city' => 'true'),
  array('id' => '160','name' => 'Череповец','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'cherepovets','db_name' => NULL,'show_city' => 'false'),
  array('id' => '161','name' => 'Черкесск','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'cherkessk','db_name' => NULL,'show_city' => ''),
  array('id' => '162','name' => 'Чита','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'chita','db_name' => NULL,'show_city' => 'false'),
  array('id' => '163','name' => 'Шахты','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'shakhty','db_name' => NULL,'show_city' => 'false'),
  array('id' => '164','name' => 'Щёлково','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'shchyelkovo','db_name' => NULL,'show_city' => 'false'),
  array('id' => '165','name' => 'Электросталь','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'elektrostal','db_name' => NULL,'show_city' => ''),
  array('id' => '166','name' => 'Элиста','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'elista','db_name' => NULL,'show_city' => ''),
  array('id' => '167','name' => 'Энгельс','inCity' => NULL,'underCity' => NULL,'whenceCity' => NULL,'whatCity' => NULL,'code' => 'engels','db_name' => NULL,'show_city' => ''),
  array('id' => '168','name' => 'Южно-Сахалинск','inCity' => 'Южно-Сахалинске','underCity' => 'Южно-Сахалинску','whenceCity' => 'Южно-Сахалинска','whatCity' => 'Южно-Сахалинск','code' => 'yuzhnosahalinsk','db_name' => NULL,'show_city' => 'true'),
  array('id' => '169','name' => 'Якутск','inCity' => '','underCity' => '','whenceCity' => '','whatCity' => '','code' => 'yakutsk','db_name' => NULL,'show_city' => 'false'),
  array('id' => '170','name' => 'Ярославль','inCity' => 'Ярославле','underCity' => 'Ярославлю','whenceCity' => 'Ярославля','whatCity' => 'Ярославский','code' => 'yaroslavl','db_name' => NULL,'show_city' => 'true')
);
